from __future__ import annotations

import json
import shutil
import sys
from pathlib import Path

EXTENSION_NAME = "keyfence.ts"
MARKER = "Generated by keyfence"
GUARDED_TOOLS = ("read", "write", "edit", "grep", "bash", "powershell")
TEMPLATE = '''// {marker} install-hooks pi. Re-run that command to update it, or
// `keyfence install-hooks pi --remove` to take it out.
import {{ spawn }} from "node:child_process";
import type {{ ExtensionAPI, ToolCallEvent }} from "@earendil-works/pi-coding-agent";

const KEYFENCE = {command};
const GUARDED = new Set({tools});

type Decision = {{ block: true; reason: string }} | undefined;

function ask(toolName: string, input: unknown): Promise<Decision> {{
  return new Promise((resolve) => {{
    const child = spawn(KEYFENCE, ["hook", "pi"], {{ stdio: ["pipe", "ignore", "pipe"] }});
    let stderr = "";
    child.stderr.on("data", (chunk: Buffer) => {{
      stderr += chunk.toString();
    }});
    child.on("error", (error: Error) => {{
      resolve({{ block: true, reason: unavailable(error.message) }});
    }});
    child.on("close", (code: number | null) => {{
      if (code === 0) resolve(undefined);
      else if (code === 2) resolve({{ block: true, reason: stderr.trim() }});
      else resolve({{ block: true, reason: unavailable(stderr.trim() || `exit ${{code}}`) }});
    }});
    child.stdin.on("error", () => {{}});
    child.stdin.end(JSON.stringify({{ tool_name: toolName, tool_input: input }}));
  }});
}}

function unavailable(detail: string): string {{
  return (
    `keyfence blocked this call because its guard could not run (${{KEYFENCE}}: ${{detail}}). ` +
    "Tell the user to check `keyfence doctor`; until then keyfence cannot tell whether this " +
    "call would expose a secret."
  );
}}

export default function (pi: ExtensionAPI) {{
  pi.on("tool_call", async (event: ToolCallEvent) => {{
    if (!GUARDED.has(event.toolName)) return;
    return ask(event.toolName, event.input);
  }});
}}
'''


def keyfence_path() -> str:
    bindir = Path(sys.executable).parent
    for name in ("keyfence", "keyfence.exe"):
        candidate = bindir / name
        if candidate.exists():
            return str(candidate)
    return shutil.which("keyfence") or "keyfence"


def extension_path(project: bool, cwd: Path | None = None) -> Path:
    base = (cwd or Path.cwd()) / ".pi" if project else Path.home() / ".pi" / "agent"
    return base / "extensions" / EXTENSION_NAME


def render(command: str | None = None) -> str:
    return TEMPLATE.format(
        marker=MARKER,
        command=json.dumps(command or keyfence_path()),
        tools=json.dumps(list(GUARDED_TOOLS)),
    )


def is_ours(path: Path) -> bool:
    try:
        return MARKER in path.read_text()
    except OSError:
        return False


def install(path: Path, command: str | None = None) -> bool:
    source = render(command)
    if path.exists() and path.read_text() == source:
        return False
    if path.exists() and not is_ours(path):
        raise FileExistsError(f"{path} was not written by keyfence; move it aside first")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(source)
    return True


def uninstall(path: Path) -> bool:
    if not is_ours(path):
        return False
    path.unlink()
    return True
